# Generated by Django 6.0.2 on 2026-02-23 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChartTradingAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=20)),
                ('signal', models.CharField(max_length=20)),
                ('confidence_score', models.FloatField()),
                ('trade_entry', models.FloatField()),
                ('trade_sl', models.FloatField()),
                ('trade_tp', models.FloatField()),
                ('reasoning', models.TextField()),
                ('pattern', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exit_price', models.FloatField(blank=True, null=True)),
                ('accuracy_status', models.CharField(choices=[('Pending', 'Pending'), ('Won', 'Won'), ('Lost', 'Lost')], default='Pending', max_length=20)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['signal'], name='api_charttr_signal_2d02ae_idx'), models.Index(fields=['created_at'], name='api_charttr_created_9e3963_idx')],
            },
        ),
        migrations.CreateModel(
            name='NewsTradingAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(default='SENTIMENT', max_length=20)),
                ('bias', models.CharField(max_length=10)),
                ('sentiment_score', models.FloatField()),
                ('impact_duration', models.CharField(max_length=15)),
                ('key_catalyst', models.TextField()),
                ('reasoning', models.TextField()),
                ('top_news', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['bias'], name='api_newstra_bias_6be006_idx'), models.Index(fields=['sentiment_score'], name='api_newstra_sentime_9703c8_idx'), models.Index(fields=['created_at'], name='api_newstra_created_724038_idx')],
            },
        ),
    ]
