# Generated by Django 6.0.2 on 2026-03-03 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charttradinganalysis',
            name='exit_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
